# Generated by Django 4.2.6 on 2024-03-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagesdb',
            name='Description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
