# Generated by Django 4.2.6 on 2024-03-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0002_packagesdb_price_alter_packagesdb_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('S_Description', models.CharField(blank=True, max_length=300, null=True)),
                ('S_Price', models.IntegerField(blank=True, null=True)),
                ('S_Image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('Destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tour.packagesdb')),
            ],
        ),
    ]
