# Generated by Django 4.2.6 on 2024-03-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0003_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='S_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='S_Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
