# Generated by Django 5.0.3 on 2024-03-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_package_description_alter_package_spot_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('U_State', models.CharField(blank=True, max_length=50, null=True)),
                ('U_Street', models.CharField(blank=True, max_length=50, null=True)),
                ('U_Town', models.CharField(blank=True, max_length=50, null=True)),
                ('U_Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('U_Email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
