# Generated by Django 5.0.3 on 2024-04-03 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_user_details_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.package'),
        ),
    ]
