# Generated by Django 5.0.3 on 2024-04-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_user_details_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.hotel'),
        ),
    ]
