# Generated by Django 5.0.3 on 2024-04-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_rename_name_feedback_n_ame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='N_ame',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
